CREATE TABLE IF NOT EXISTS `user` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `userName` VARCHAR(255) NOT NULL DEFAULT '',
   `avatar` VARCHAR(100) NOT NULL DEFAULT '',
   `level` INT NOT NULL DEFAULT 0,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `artical` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `content` VARCHAR(255) NOT NULL DEFAULT '',
   `userId` INT NOT NULL,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `level` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `name` VARCHAR(255) NOT NULL DEFAULT '',
   `value` INT NOT NULL,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `trends` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `content` VARCHAR(255) NOT NULL DEFAULT '',
   `picList` VARCHAR(255) NOT NULL DEFAULT '',
   `type` INT NOT NULL DEFAULT 0,
   `userId` INT NOT NULL,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user-trends` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `trendId` INT NOT NULL,
   `userId` INT NOT NULL,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user-artical` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `articalId` INT NOT NULL,
   `userId` INT NOT NULL,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `trend-subTrend` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `trendId` INT NOT NULL,
   `subTrendId` INT NOT NULL,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `artical-trend` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `articalId` INT NOT NULL,
   `trendId` INT NOT NULL,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `authLog` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `userId` INT NOT NULL,
   `authDate` VARCHAR(255) NOT NULL,
   `authLevel` INT NOT NULL,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;
