CREATE TABLE IF NOT EXISTS `user` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `userName` VARCHAR(255) NOT NULL DEFAULT '',
   `avatar` VARCHAR(100) NOT NULL DEFAULT '',
   `level` INT NOT NULL DEFAULT 0,
   `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `tag` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `name` VARCHAR(255) NOT NULL DEFAULT '',
   `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user_tag` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `userId` INT NOT NULL,
   `tagId` INT NOT NULL,
   `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `artical` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `content` VARCHAR(255) NOT NULL DEFAULT '',
   `userId` INT NOT NULL,
   `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `level` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `name` VARCHAR(255) NOT NULL DEFAULT '',
   `value` VARCHAR(255) NOT NULL DEFAULT '',
   `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `trends` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `content` VARCHAR(255) NOT NULL DEFAULT '',
   `picList` VARCHAR(255) NOT NULL DEFAULT '',
   `type` INT NOT NULL DEFAULT 0,
   `userId` INT NOT NULL,
   `level` INT NOT NULL,
   `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user_trends` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `trendId` INT NOT NULL,
   `userId` INT NOT NULL,
   `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user_artical` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `articalId` INT NOT NULL,
   `userId` INT NOT NULL,
   `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `trend_subTrend` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `trendId` INT NOT NULL,
   `subTrendId` INT NOT NULL,
   `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `artical_trend` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `articalId` INT NOT NULL,
   `trendId` INT NOT NULL,
   `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `authLog` (
   `id` INT UNSIGNED AUTO_INCREMENT,
   `userId` INT NOT NULL,
   `authDate` VARCHAR(255) NOT NULL,
   `authLevel` INT NOT NULL,
   `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
) DEFAULT CHARSET=utf8;
